import { HttpClient } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { Observable, map } from 'rxjs';
import { Deck, Sport, STAT_KEYS } from '../models/card.model';

/**
 * Loads a deck from the static JSON the refresh job writes into public/data.
 * There is no API in v1 — the cron job rewrites these files, the app just reads
 * them, so the demo works with no server and no keys.
 */
@Injectable({ providedIn: 'root' })
export class DeckService {
  private readonly http = inject(HttpClient);

  load(sport: Sport): Observable<Deck> {
    return this.http
      .get<unknown>(`data/deck.${sport}.json`)
      .pipe(map((raw) => assertDeck(raw, sport)));
  }
}

/**
 * Validates a deck at the trust boundary. The file is regenerated by an
 * automated job against third-party data, so a malformed card should fail
 * loudly here rather than surface as a blank row mid-game.
 */
export function assertDeck(raw: unknown, expectedSport: Sport): Deck {
  const deck = raw as Deck;
  if (!deck || typeof deck !== 'object' || !Array.isArray(deck.cards)) {
    throw new Error('Deck is malformed: expected a cards array.');
  }
  if (deck.sport !== expectedSport) {
    throw new Error(`Deck sport mismatch: wanted ${expectedSport}, got ${deck.sport}.`);
  }
  if (deck.cards.length < 2) {
    throw new Error('Deck needs at least two cards to play.');
  }

  for (const card of deck.cards) {
    for (const key of STAT_KEYS) {
      const cell = card.stats?.[key];
      if (!cell || typeof cell.percentile !== 'number') {
        throw new Error(`Card ${card.id ?? '?'} is missing stat "${key}".`);
      }
    }
  }

  return deck;
}
